## @section Logstash configuration
## Discarded if customConfig is enabled
##
logstash:
  ## @section logstash.instances Logstash instances
  ##
  instances:
    ## @param logstash.instances[0].url Logstash URL for the first instance
    ##
    - url: "http://logstash:9600"
    ## @param logstash.instances[1].url Logstash URL for the second instance
    ##
    - url: "http://logstash2:9600"
  ## @section Logstash exporter server configuration
  ##
  server:
    ## @param logstash.server.host Host for the logstash exporter server
    ##
    host: "0.0.0.0"
    ## @param logstash.server.port Port for the logstash exporter server
    ##
    port: 9198
  ## @section Logging configuration
  ##
  logging:
    ## @param logstash.logging.level Logstash exporter logging level
    ##
    level: "info"
  ## @section Kubernetes controller configuration
  ##
  kubernetes:
    ## @param logstash.kubernetes.enabled Enable Kubernetes controller
    ##
    enabled: false
    ## @param logstash.kubernetes.namespaces Namespaces to watch (empty for all)
    ##
    namespaces: []
    ## @section Resource type monitoring configuration
    ##
    resources:
      ## @section Pod monitoring configuration
      ##
      pods:
        ## @param logstash.kubernetes.resources.pods.enabled Enable pod monitoring
        ##
        enabled: true
        ## @param logstash.kubernetes.resources.pods.annotationPrefix Prefix for pod annotations
        ##
        annotationPrefix: "logstash-exporter.io"
      ## @section Service monitoring configuration
      ##
      services:
        ## @param logstash.kubernetes.resources.services.enabled Enable service monitoring
        ##
        enabled: false
        ## @param logstash.kubernetes.resources.services.annotationPrefix Prefix for service annotations
        ##
        annotationPrefix: "logstash-exporter.io"
    ## @param logstash.kubernetes.resyncPeriod Resync period for the controller cache
    ##
    resyncPeriod: 10m
    ## @param logstash.kubernetes.scrapeInterval Interval to scrape logstash instances
    ##
    scrapeInterval: 15s
    ## @param logstash.kubernetes.logstashURLAnnotation Annotation containing logstash URL
    ##
    logstashURLAnnotation: "logstash-exporter.io/url"
    ## @param logstash.kubernetes.logstashUsernameAnnotation Annotation for logstash username
    ##
    logstashUsernameAnnotation: "logstash-exporter.io/username"
    ## @param logstash.kubernetes.logstashPasswordAnnotation Annotation for logstash password
    ##
    logstashPasswordAnnotation: "logstash-exporter.io/password"

## @section Custom logstash-exporter configuration
## Overrides the default .logstash section
##
customConfig:
  ## @param customConfig.enabled Enable custom configuration
  ##
  enabled: false
  ## @param customConfig.config Custom configuration
  ##
  config: |
    logstash:
      instances:
        - "http://logstash:9600"
      server:
        host: "0.0.0.0"
        port: 9198
      logging:
        level: "info"
      kubernetes:
        enabled: false
        namespaces: []
        resources:
          pods:
            enabled: true
            annotationPrefix: "logstash-exporter.io"
          services:
            enabled: false
            annotationPrefix: "logstash-exporter.io"
        resyncPeriod: 10m
        scrapeInterval: 15s
        logstashURLAnnotation: "logstash-exporter.io/url"

## @section Image settings
##
image:
  ## @param image.repository Image repository
  ##
  repository: "kuskoman/logstash-exporter"
  ## @param image.tag Image tag, if not set the appVersion is used
  ##
  tag: ""
  ## @param image.pullPolicy Image pull policy
  ## Options: Always, Never, IfNotPresent
  ##
  pullPolicy: IfNotPresent
  ## @param image.controllerRepository Image repository for the controller
  ## If not set, will use repository with "-controller" suffix
  ##
  controllerRepository: ""

## @param fullnameOverride Override the fullname of the chart
##
fullnameOverride: ""

## @section Deployment settings
##
deployment:
  ## @param deployment.replicas Number of replicas for the deployment
  ##
  replicas: 1
  ## @param deployment.restartPolicy Restart policy for the deployment.
  ## Options: Always, OnFailure, Never
  ##
  restartPolicy: Always
  ## @param deployment.annotations Additional deployment annotations
  ##
  ## Example:
  ## annotations:
  ##   kubernetes.io/foo: bar
  ##
  annotations: {}
  ## @param deployment.labels Additional deployment labels
  ##
  ## Example:
  ## labels:
  ##   foo: bar
  ##
  labels: {}
  ## @param deployment.pullSecret Kubernetes secret for pulling the image
  ##
  pullSecret: []
  ## @param deployment.resources Resource requests and limits
  ##
  resources: {}
  ## @param deployment.nodeSelector Node selector for the deployment
  ##
  nodeSelector: {}
  ## @param deployment.tolerations Tolerations for the deployment
  ##
  tolerations: []
  ## @param deployment.podAnnotations Additional pod annotations
  ##
  podAnnotations: {}
  ## @param deployment.podLabels Additional pod labels
  ##
  podLabels: {}
  ## @param deployment.affinity Affinity for the deployment
  ##
  affinity: {}
  ## @param deployment.env Additional environment variables
  ##
  env: {}
  ## @param deployment.envFrom Additional environment variables from config maps or secrets
  ##
  envFrom: []
  ## @param deployment.priorityClassName Priority class name for the deployment
  ##
  priorityClassName: ""
  ## @param deployment.dnsConfig DNS configuration for the deployment
  ##
  dnsConfig: {}
  ## @param deployment.securityContext Security context for the deployment
  ##
  securityContext: {}
  ## @param deployment.podSecurityContext Security context for the deployment that only applies to the pod
  ##
  podSecurityContext: {}
  ## @param deployment.containerSecurityContext Security context for the deployment that only applies to the container
  ##
  containerSecurityContext: {}
  ## @section Liveness probe settings
  ##
  livenessProbe:
    httpGet:
      ## @param deployment.livenessProbe.httpGet.path Path for liveness probe
      ##
      path: /health
      ## @param deployment.livenessProbe.httpGet.port Port for liveness probe
      ##
      port: 9198
    ## @param deployment.livenessProbe.initialDelaySeconds Initial delay for liveness probe
    ##
    initialDelaySeconds: 30
    ## @param deployment.livenessProbe.periodSeconds Period for liveness probe
    ##
    periodSeconds: 10
    ## @param deployment.livenessProbe.timeoutSeconds Timeout for liveness probe
    ##
    timeoutSeconds: 5
    ## @param deployment.livenessProbe.successThreshold Success threshold for liveness probe
    ##
    successThreshold: 1
    ## @param deployment.livenessProbe.failureThreshold Failure threshold for liveness probe
    ##
    failureThreshold: 3
  ## @param deployment.readinessProbe Readiness probe configuration
  ##
  readinessProbe: {}
  ## @section Rolling update settings
  ##
  rollingUpdate:
    ## @param deployment.rollingUpdate.maxSurge Maximum surge for rolling update
    ##
    maxSurge: 1
    ## @param deployment.rollingUpdate.maxUnavailable Maximum unavailable for rolling update
    ##
    maxUnavailable: 0

## @section Service settings
##
service:
  ## @param service.type Service type
  ##
  type: ClusterIP
  ## @param service.port Service port
  ##
  port: 9198
  ## @param service.annotations Additional service annotations
  ##
  annotations: {}
  ## @param service.labels Additional service labels
  ##
  labels: {}

## @section ServiceAccount settings
##
serviceAccount:
  ## @param serviceAccount.enabled Enable service account creation
  ##
  enabled: false
  ## @param serviceAccount.create Create service account
  ##
  create: false
  ## @param serviceAccount.name Service account name
  ##
  name: ""
  ## @param serviceAccount.annotations Additional service account annotations
  ##
  annotations: {}

## @section RBAC settings for Kubernetes controller
##
rbac:
  ## @param rbac.create Create RBAC resources
  ##
  create: false
  ## @param rbac.rules Custom rules to add to the ClusterRole
  ##
  rules:
    - apiGroups: [""]
      resources: ["pods", "services"]
      verbs: ["get", "list", "watch"]
