logstash:
  instances:
    - url: "http://localhost:9600"
      httpInsecure: false
    - url: "https://logstash-secure:9600"
      httpInsecure: true
      name: "secure_instance"
  timeout: 3s
server:
  host: "127.0.0.1"
  port: 9200
  # TLS/HTTPS configuration (optional)
  # enableSSL: true
  # certFile: "/path/to/cert.pem"
  # keyFile: "/path/to/key.pem"
logging:
  level: "info"
  format: "text"
# Kubernetes controller configuration (optional)
kubernetes:
  enabled: false
  # Watch only specific namespaces (empty watches all)
  # namespaces:
  #   - default
  #   - monitoring
  # Define which resource types to monitor
  resources:
    # Pod monitoring configuration
    pods:
      enabled: true
      annotationPrefix: "logstash-exporter.io"
    # Service monitoring configuration
    services:
      enabled: false
      annotationPrefix: "logstash-exporter.io"
  resyncPeriod: 10m
  scrapeInterval: 15s
  logstashURLAnnotation: "logstash-exporter.io/url"
  logstashUsernameAnnotation: "logstash-exporter.io/username"
  logstashPasswordAnnotation: "logstash-exporter.io/password"
  # kubeConfig: /path/to/kubeconfig # Optional: path to kubeconfig file for running outside cluster
