FROM cosmtrek/air:v1.64.4 as air


FROM golang:1.25.4-alpine3.21

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=air /go/bin/air /go/bin/air

EXPOSE 9198

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:9198/healthcheck

ENTRYPOINT ["/go/bin/air", "-c", ".air.toml"]
