FROM cosmtrek/air:v1.52.3 as air

FROM golang:1.22.5-alpine3.20

WORKDIR /app

RUN apk add --no-cache curl

COPY --from=air /go/bin/air /go/bin/air

EXPOSE 9198

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:9198/healthcheck

ENTRYPOINT ["/go/bin/air", "-c", ".air.toml"]
