name: Bug Report
description: Report an issue with Logstash Exporter
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the Issue
      description: Please provide a clear and concise description of what the issue is.
      placeholder: Describe the issue here
    validations:
      required: true
  - type: input
    id: version-logstash-exporter
    attributes:
      label: Version of logstash-exporter, or logstash-exporter Image
      description: Please provide the version of logstash-exporter or the logstash-exporter image you are using.
      placeholder: ex. v1.6.1
    validations:
      required: true
  - type: input
    id: version-chart
    attributes:
      label: Version of Chart (if applicable)
      description: If you are using a Helm chart for deployment, please provide the chart version here.
      placeholder: ex. v2.3.1
    validations:
      required: false
  - type: input
    id: operating-system
    attributes:
      label: Operating System/Environment
      description: Please provide information about your operating system or environment, including OS version, deployment environment, etc., if applicable.
      placeholder: ex. Ubuntu 20.04, Kubernetes 1.19
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem. This will be automatically formatted into code, so no need for backticks.
      render: sh
    validations:
      required: false
