#!/usr/bin/env bash

# execute: ./scripts/add_descriptions_to_readme.sh

# enable regex (see: https://stackoverflow.com/a/42740385)
shopt -s extglob

scriptName="$(dirname "$0")/$(basename "$0")"

function getHelp() { # get descriptions and commands from Makefile
	i=0
	commands=()
	descriptions=()

	while read -r line; do
		if (( i % 2 == 0 ));
			then
				descriptions+=( "${line//#:*( )}" )
			else
				commands+=( "$(echo "$line" | cut -d : -f 1)" )
		fi
		((i++))
	done < <(
		# https://stackoverflow.com/a/59087509
		grep -B1 -E "^[a-zA-Z0-9_-]+:([^\=]|$)" ./Makefile \
		| grep -v -- --
	)
}

FILE=README.md

# returns `commands` and `descriptions` arrays
getHelp

startLine=$(( $( grep -n "^#### Available Commands" $FILE | cut -d : -f 1 ) + 2 ))
endLine=$(( $( grep -n "^#### File Structure" $FILE | cut -d : -f 1 ) - 2 ))

# Updates "Available Commands" section
if (( startLine <= endLine));
then
	# Deletes previous descriptions
	sed -i "$startLine,${endLine}d" "$FILE"
fi

function createMultipleAsterisks() {
	numOfAsterisks=$1
	asterisks=$( eval printf "\*%.0s" "{1..$numOfAsterisks}" )
	echo "$asterisks"
}

function printAvailableCommands() {
	curLine=$startLine
	stringToWrite="<!--- GENERATED by $scriptName --->"
	commentLen=$(( ${#stringToWrite} - 11 ))
	i=0

	sed -i "${curLine}i\\${stringToWrite}" "$FILE"

	# https://www.shellcheck.net/wiki/SC2219
	(( curLine++ )) || true

	# empty line
	sed -i "${curLine}i\\ " "$FILE"

	(( curLine++ )) || true

	while (( i < ${#commands[@]} ))
	do
		stringToWrite="- \`make ${commands[$i]}\`: ${descriptions[$i]}."
		stringToWrite=${stringToWrite//\'/\\\'}
		echo "$stringToWrite"
		sed -i "${curLine}i\\${stringToWrite}" "$FILE"
		(( curLine++ )) || true

		(( i++ )) || true
	done

	# empty line
	sed -i "${curLine}i\\ " "$FILE" 
	(( curLine++ )) || true

	# multiple '*'
	asterisks=$(createMultipleAsterisks $commentLen)
	stringToWrite="<!--- $asterisks --->" 
	sed -i "${curLine}i\\${stringToWrite}" "$FILE"

	(( curLine++ )) || true
}

echo 'Updating "Available Commands" section...'

printAvailableCommands

# Updates "Example Usage" section:
startLine=$(( $(grep -n "^#### Example Usage" "$FILE" | cut -d : -f 1) + 2 ))
endLine=$(( $(grep -n "^## Helper Scripts" "$FILE" | cut -d : -f 1) - 2 ))

if (( startLine <= endLine));
then
	# Deletes of previous descriptions
	sed -i "$startLine,${endLine}d" "$FILE" 
fi

function printExampleUsage() {
	curLine=$startLine
	stringToWrite="<!--- GENERATED by $scriptName --->"
	commentLen=$(( ${#stringToWrite} - 11 ))
	i=0

	sed -i "${curLine}i\\${stringToWrite}" "$FILE"
	(( curLine++ )) || true

	# empty line
	sed -i "${curLine}i\\ " "$FILE"  
	(( curLine++ )) || true

	while (( i < ${#commands[@]} ))
	do
		stringToWrite="${descriptions[$i]}:"
		sed -i "${curLine}i\\${stringToWrite}" "$FILE"
		(( curLine++ )) || true

		sed -i "${curLine}i\\ " "$FILE"
		(( curLine++ )) || true

		# 4 spaces left for tab (DON'T CHANGE IT!)
		stringToWrite="    make ${commands[$i]}" 
		sed -i "${curLine}i\\${stringToWrite}" "$FILE"
		(( curLine++ )) || true

		sed -i "${curLine}i\\ " "$FILE"
		(( curLine++ )) || true

		(( i++ )) || true
	done

	asterisks=$(createMultipleAsterisks $commentLen)
	stringToWrite="<!--- $asterisks --->" 
	sed -i "${curLine}i\\${stringToWrite}" "$FILE"
	(( curLine++ )) || true
}

echo 'Updating "Example Usage" section...'

printExampleUsage

echo 'Done.'

