apiVersion: v2
name: logstash-integration-test-chart
description: Helm chart for testing the logstash-exporter Helm chart
type: application
version: 0.1.0
dependencies:
  - name: logstash
    version: "^8.5.1"
    repository: https://helm.elastic.co
    condition: logstash.enabled
  - name: prometheus
    version: "^27.5.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: logstash-exporter
    version: "*"
    repository: file://../../chart/
    condition: logstash-exporter.enabled
