apiVersion: v2
name: logstash-integration-test-chart
description: Helm chart for testing the logstash-exporter Helm chart
type: application
version: 0.1.0
dependencies:
  - name: logstash
    version: "^8.5.1"
    repository: https://helm.elastic.co
    condition: logstash.enabled
  # we are replacing elasticsearch with apache for testing purposes
  - name: apache
    version: "^11.2.10"
    repository: https://charts.bitnami.com/bitnami
    condition: apache.enabled
  - name: prometheus
    version: "^25.24.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: logstash-exporter
    version: "*"
    repository: file://../../chart/
    condition: logstash-exporter.enabled
